homeassistant:
  unit_system: metric
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: !secret home_timezone
  customize: !include_dir_merge_named includes/customizations
  packages: !include_dir_named includes/packages

python_script:
mobile_app:

updater:
  reporting: false

config:
system_health:
history:
sun:

lovelace: !include includes/lovelace.yaml

logger:
  default: info

#logbook:
#  exclude:
#    entities:
#      - sensor.uptime
#      - sensor.time
#      - sensor.date
#      - sensor.date_time
#      - sensor.sun_dawn
#      - sensor.sun_dusk
#      - sensor.sun_elevation
#      - sensor.xiaomi_map
#      - binary_sensor.test
#      - sensor.test_uptime_sensor
#      - binary_sensor.test
#    domains:
#      - sun
#      #- sensor
#      - switch
#      - media_player
#      - weather

recorder: !include includes/db.yaml

frontend:
  themes: !include_dir_merge_named themes

auto_backup:
  auto_purge: true
  backup_timeout: 10000  # 40 minutes, needs to be converted to seconds.
  keep_days: 7

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_key
  name: Duplicator 6
  number_of_tools: 1
  bed: true

device_tracker:
  - platform: snmp
    host: !secret mikrotik_ip
    #    username: public
    community: !secret snmp_user
    auth_key: !secret snmp_auth_key
    priv_key: !secret snmp_priv_key
    #auth_protocol: !secret snmp_auth_protocol
    #priv_protocol: !secret snmp_priv_protocol
    baseoid: 1.3.6.1.4.1.14988.1.1.1.5.1.1
    interval_seconds: 60
    consider_home: 120
    new_device_defaults:
      track_new_devices: false

stream:
ffmpeg:

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret octoprint_image_url
    mjpeg_url: !secret octopi_mjpeg_url

#  - platform: xiaomi_cloud_map_extractor
#    host: !secret xiaomi_vacuum_ip
#    token: !secret xiaomi_vacuum_token
#    username: !secret xiaomi_cloud_username
#    password: !secret xiaomi_cloud_password
#    country: "ru"


wake_on_lan:

media_player:
  - platform: sox
    name: Roborock
    host: !secret xiaomi_vacuum_ip
    port: 7777 # Optional

tts:
  - platform: rhvoice
    host: !secret host_tts
    port: 8080 # Optional
    format: 'mp3' # Optional, wav|mp3|opus|flac
    pitch: 50 # Optional, 0..100
    rate: 80 # Optional, 0..100
    voice: 'elena' # Optional, default is 'anna' (russian)
    volume: 40 # Optional, 0..100
  
webostv: !include includes/webostv.yaml

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_bot_chat_id

telegram_bot:
  - platform: polling
    #proxy_url: !secret telegram_proxy_url
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id

mikrotik:
  host: !secret mikrotik_ip
  username: !secret mikrotik_user
  password: !secret mikrotik_pass

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

weather:
  - platform: gismeteo
#  - platform: yandex_weather
#    api_key: !secret yandex_weather_api_key

switch: !include_dir_merge_list includes/switches
sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include_dir_merge_list includes/binary_sensors
#light:          !include_dir_merge_list includes/lights
climate: !include_dir_merge_list includes/climate
automation: !include_dir_merge_list includes/automations
group: !include includes/groups.yaml
#media_player:   !include includes/media_player.yaml
#yeelight:       !include includes/yeelight.yaml
script: !include includes/scripts.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_datetime: !include includes/input_datetime.yaml
input_select: !include includes/input_select.yaml
input_text: !include includes/input_text.yaml
#panel_iframe:   !include includes/panel_iframe.yaml
#timer:          !include includes/timer.yaml
#scene:          !include includes/scenes.yaml
