title: Home

views: 
  - !include includes/lovelace/home.yaml
  - !include includes/lovelace/media.yaml
  - !include includes/lovelace/vacuum.yaml
  - !include includes/lovelace/zigbee.yaml
  - !include includes/lovelace/energy.yaml
  - !include includes/lovelace/system.yaml
  - !include includes/lovelace/network.yaml
  - !include includes/lovelace/energy_input.yaml
  - !include includes/lovelace/3d.yaml
  - !include includes/lovelace/covid.yaml
  - !include includes/lovelace/settings.yaml

