### Нужно отслеживать каждое изменение PIR сенсора. Желательно это сделать напрямую из топика mqtt
### https://www.zigbee2mqtt.io/integration/home_assistant.html
### https://github.com/home-assistant/core/issues/20358
### Очень удачное решение!
- alias: Aqara WC ON
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/WC move"
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.occupancy == true }}"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.wc_light_left
        - switch.wc_light_right

### опять же выкрутасы с PIR сенсором, нужно организовать задержку на выключение
### Можно получать этот статус с самого сенсора, но тогда = 1 мин
### Значение берем со своего бинарного сенсора, время перехода которого задается вручную = 10сек
### самое удачное решение!!!
- alias: Aqara WC OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.wc_door_contact
      to: "on"
    - platform: state
      entity_id: binary_sensor.wc_pir
      to: "off"
  condition:
    - condition: state
      entity_id: binary_sensor.wc_door_contact
      state: "on"
  action:
    - delay: "0:00:15" # Ждем 15 сек и проверяем еще раз. Может уже кто-то забежал? Время жизни бинарного сенсора + 5 сек для верности
    - choose:
      - conditions:
        - condition: state
          entity_id: binary_sensor.wc_door_contact
          state: "on"
        - condition: state
          entity_id: binary_sensor.wc_pir
          state: "off"
        sequence:
          - service: switch.turn_off
            entity_id:
              - switch.wc_light_left
              - switch.wc_light_right

- alias: Aqara Hallway ON
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_door_contact
      to: "on"
  condition:
  action:
    - service: switch.turn_on
      entity_id:
        - switch.hallway_light

- alias: Aqara Hallway OFF
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_door_contact
      to: "off"
  condition:
  action:
    - delay: "0:03:00"
    - service: switch.turn_off
      entity_id:
        - switch.hallway_light

- alias: Terrarium light ON button
  trigger:
    - platform: state
      entity_id: sensor.button_action
      to: "single"
  condition:
  action:
    - service: light.turn_on
      entity_id:
        - light.terrarium_master_lamp

- alias: Terrarium light OFF button
  trigger:
    - platform: state
      entity_id: sensor.button_action
      to: "double"
  condition:
  action:
    - service: light.turn_off
      entity_id:
        - light.terrarium_master_lamp

- alias: Terrarium TV OFF button
  trigger:
    - platform: state
      entity_id: sensor.button_action
      to: "triple"
  condition:
  action:
    - service: webostv.button
      data:
        entity_id: media_player.tv_lounge
        button: "BACK"
    - delay: "0:0:05"
    - service: webostv.command
      data:
        entity_id: media_player.tv_lounge
        command: system/turnOff

- alias: WC light key
  trigger:
    - platform: state
      entity_id: sensor.key_action
      to: "single"
  condition:
  action:
    - service: switch.toggle
      entity_id:
        - switch.wc_light_left
        - switch.wc_light_right
