### Edifire 2700 хавает из розетки постоянно около 20вт, даже когда не используется
### Включаем Edifire 2700 вместе с телевизором
- alias: Edifire 2700 ON
  trigger:
    - platform: state
      entity_id: media_player.tv_lounge
      to: "on"
  condition:
  action:
    - service: switch.turn_on
      entity_id: switch.hiper_iot04_edifire2700_relay
    - delay: 00:00:08
    - service: webostv.button
      entity_id: media_player.tv_lounge
      data:
        button: "ENTER"

#    - service: notify.telegram
#      data:
#        title: "Edifire On"
#        message: "Питание розетки включено"


### Выключаем Edifire 2700 когда телевизор выключается
- alias: Edifire 2700 OFF
  trigger:
    - platform: state
      entity_id: media_player.tv_lounge
      to: "off"
  condition:
  action:
#    - service: notify.telegram
#      data:
#        title: "Edifire Off"
#        message: "WiFi у телека отключился"
    - delay: "00:01:00" ### Исключаем дребезг, в момент обновления состояния entity: media_player
    - choose:
        - conditions:
            - condition: state
              entity_id: media_player.tv_lounge
              state: "off"
          sequence:
            - service: switch.turn_off
              entity_id: switch.hiper_iot04_edifire2700_relay

