### Выключаем розетку ПК.
### жрет 5-12 Вт энергии постоянно принтер WiFi, БП ПК и пр
### Как только нагрузка падает ниже  10 Вт, отключаем все!
### Экономия 100р в год, но зато не фонят
- alias: PC balkoon OFF
#  alias: PC balkoon OFF
  trigger:
    - platform: numeric_state
      entity_id: sensor.digma_100s_pc_power
      below: 10
  condition:
  action:
    - service: switch.turn_off
      entity_id: switch.digma_100s_pc_relay