- alias: Smartmi Humidifier 2 low level
  trigger:
    - platform: numeric_state
      entity_id: fan.xiaomi_miio_device
      value_template: "{{ state.attributes.depth }}"
      below: 50
  condition:
  action:
    - service: notify.telegram
      data:
        title: "Smartmi Humidifier 2 low level"
        message: "Просто добавь воды!"
    - choose:
        - conditions:
            - condition: time
              after: "06:00:00"
              before: "23:00:00"
          sequence:
            - service: media_player.play_media
              entity_id: media_player.yandex_station_ff98f029b718c14a5be213b8
              data:
                media_content_id: Добавьте воды в увлажнитель!
                media_content_type: text
