- alias: "HACS Persistent Notification"
  initial_state: "on"
  trigger:
    platform: numeric_state
    entity_id: sensor.hacs
    above: 0
  action:
    - service: notify.telegram
      data:
        title: "HACS updates are available"
        message: >
          {% for item in states.sensor.hacs.attributes.repositories %}
            {{ item.display_name }} {{ item['installed version'] }} -> {{ item['available version'] }}
          {% endfor %}

- alias: "HA Persistent Notification"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.update_available
      to: "on"
  action:
    - service: notify.telegram
      data:
        title: "HA Upgrade is Available"
        message: "Upgrade from {{ states('sensor.ha_current') }} to {{ states('sensor.ha_latest') }} is available"

- alias: "HA Persistent Notification"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.rb3011_need_update
      to: "off"
  action:
    - service: notify.telegram
      data:
        title: "Mikrotik RouterOS Update"
        message: "Upgrade from {{ states('sensor.rb3011_firmware') }} to {{ states('sensor.routeros_latest_release') }} is available"