- alias: Sound Level Down
  trigger:
    platform: time
    at: "23:00:00"
  condition:
  action:
    - service: media_player.volume_set
      entity_id: media_player.yandex_station_ff98f029b718c14a5be213b8
      data:
        volume_level: 0.3

- alias: Sound Level Up
  trigger:
    platform: time
    at: "06:00:00"
  condition:
  action:
    - service: media_player.volume_set
      entity_id: media_player.yandex_station_ff98f029b718c14a5be213b8
      data:
        volume_level: 0.5

- alias: Скажи холодно
  mode: restart
  trigger:
    - platform: numeric_state
      entity_id: sensor.balkoon_warm_floor_bme280_temperature
      below: 20
  condition:
  action:
    - service: media_player.play_media
      entity_id: media_player.yandex_station_ff98f029b718c14a5be213b8
      data:
        media_content_id: На балконе очень холодно, закройте окно!
        media_content_type: text
