#- platform: snmp
#  name: mik_eth3_on
#  host: !secret mikrotik_ip
#  community: !secret snmp_community
#  auth_key: !secret snmp_auth_key
#  priv_key: !secret snmp_priv_key
#  baseoid: 1.3.6.1.4.1.14988.1.1.18.1.1.2.7
#
#- platform: snmp
#  name: mik_eth3_off
#  host: !secret mikrotik_ip
#  community: !secret snmp_community
#  auth_key: !secret snmp_auth_key
#  priv_key: !secret snmp_priv_key
#  baseoid: 1.3.6.1.4.1.14988.1.1.18.1.1.2.6

- platform: template
  switches:
    rb3011_eth1:
      friendly_name: "rb3011_eth1_wan"
      value_template: "{{ is_state('sensor.rb3011_status_eth1', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth1_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth1
        - service: homeassistant.update_entity
          data:
            entity_id: binary_sensor.google_dns
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth1_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth1
        - service: homeassistant.update_entity
          data:
            entity_id: binary_sensor.google_dns

- platform: template
  switches:
    rb3011_eth2:
      friendly_name: "rb3011_eth2"
      value_template: "{{ is_state('sensor.rb3011_status_eth2', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth2_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth2
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth2_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth2

- platform: template
  switches:
    rb3011_eth3:
      friendly_name: "rb3011_eth3"
      value_template: "{{ is_state('sensor.rb3011_status_eth3', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth3_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth3
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth3_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth3

- platform: template
  switches:
    rb3011_eth4:
      friendly_name: "rb3011_eth4"
      value_template: "{{ is_state('sensor.rb3011_status_eth4', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth4_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth4
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth4_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth4

- platform: template
  switches:
    rb3011_eth5:
      friendly_name: "rb3011_eth5"
      value_template: "{{ is_state('sensor.rb3011_status_eth5', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth5_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth5
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth5_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth5

- platform: template
  switches:
    rb3011_eth6:
      friendly_name: "rb3011_eth6"
      value_template: "{{ is_state('sensor.rb3011_status_eth6', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth6_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth6
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth6_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth6

- platform: template
  switches:
    rb3011_eth7:
      friendly_name: "rb3011_eth7"
      value_template: "{{ is_state('sensor.rb3011_status_eth7', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth7_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth7
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth7_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth7

- platform: template
  switches:
    rb3011_eth8:
      friendly_name: "rb3011_eth8"
      value_template: "{{ is_state('sensor.rb3011_status_eth8', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth8_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth8
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth8_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth8

- platform: template
  switches:
    rb3011_eth9:
      friendly_name: "rb3011_eth9"
      value_template: "{{ is_state('sensor.rb3011_status_eth9', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth9_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth9
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth9_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth9

- platform: template
  switches:
    rb3011_eth10:
      friendly_name: "rb3011_eth10"
      value_template: "{{ is_state('sensor.rb3011_status_eth10', '1') }}"
      turn_on:
        - service: mikrotik.run_script
          data:
            name: eth10_on
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth10
      turn_off:
        - service: mikrotik.run_script
          data:
            name: eth10_off
        - service: homeassistant.update_entity
          data:
            entity_id: sensor.rb3011_status_eth10
