input_boolean:
  backup_shedule:
    name: "Регулярное резервное копирование"
    icon: "mdi:timer-outline"

automation:
  - alias: Backup Everyday
    #  initial_state: true
    trigger:
      - platform: time
        at: "04:15"
    condition:
      - condition: state
        entity_id: input_boolean.backup_shedule
        state: "on"
    action:
      - service: auto_backup.snapshot_full
        data_template:
          name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
          keep_days: 7
    #      exclude:
    #        addons:
    #          - Portainer
    #        folders:
    #          - Local add-ons
    #          - share
