#Обязательно нужны ТАРИФЫ!!! Иначе счетчики нельзя обнулять!!!

utility_meter:

  energy_hourly_edifire2700:
    source: sensor.hiper_iot04_edifire2700_total_daily_energy
    cycle: hourly
    tariffs: stnd
  energy_daily_edifire2700:
    source: sensor.hiper_iot04_edifire2700_total_daily_energy
    cycle: daily
    tariffs: stnd
  energy_monthly_edifire2700:
    source: sensor.hiper_iot04_edifire2700_total_daily_energy
    cycle: monthly
    tariffs: stnd
  energy_yearly_edifire2700:
    source: sensor.hiper_iot04_edifire2700_total_daily_energy
    cycle: yearly
    tariffs: stnd

  energy_hourly_washer:
    source: sensor.hiper_iot04_washer_total_daily_energy
    cycle: hourly
    tariffs: stnd
  energy_daily_washer:
    source: sensor.hiper_iot04_washer_total_daily_energy
    cycle: daily
    tariffs: stnd
  energy_monthly_washer:
    source: sensor.hiper_iot04_washer_total_daily_energy
    cycle: monthly
    tariffs: stnd
  energy_yearly_washer:
    source: sensor.hiper_iot04_washer_total_daily_energy
    cycle: yearly
    tariffs: stnd

  energy_hourly_water_heater:
    source: sensor.hiper_iot04_water_heater_total_daily_energy
    cycle: hourly
    tariffs: stnd
  energy_daily_water_heater:
    source: sensor.hiper_iot04_water_heater_total_daily_energy
    cycle: daily
    tariffs: stnd
  energy_monthly_water_heater:
    source: sensor.hiper_iot04_water_heater_total_daily_energy
    cycle: monthly
    tariffs: stnd
  energy_yearly_water_heater:
    source: sensor.hiper_iot04_water_heater_total_daily_energy
    cycle: yearly
    tariffs: stnd

  energy_hourly_4:
    source: sensor.hiper_iot04_4_total_daily_energy
    cycle: hourly
    tariffs: stnd
  energy_daily_4:
    source: sensor.hiper_iot04_4_total_daily_energy
    cycle: daily
    tariffs: stnd
  energy_monthly_4:
    source: sensor.hiper_iot04_4_total_daily_energy
    cycle: monthly
    tariffs: stnd
  energy_yearly_4:
    source: sensor.hiper_iot04_4_total_daily_energy
    cycle: yearly
    tariffs: stnd

  energy_hourly_5:
    source: sensor.hiper_iot04_5_total_daily_energy
    cycle: hourly
    tariffs: stnd
  energy_daily_5:
    source: sensor.hiper_iot04_5_total_daily_energy
    cycle: daily
    tariffs: stnd
  energy_monthly_5:
    source: sensor.hiper_iot04_5_total_daily_energy
    cycle: monthly
    tariffs: stnd
  energy_yearly_5:
    source: sensor.hiper_iot04_5_total_daily_energy
    cycle: yearly
    tariffs: stnd

###############################################################################
  energy_hourly_tvps4:
    source: sensor.digma_100s_tvps4_total_daily_energy
    cycle: hourly
    tariffs: stnd
  energy_daily_tvps4:
    source: sensor.digma_100s_tvps4_total_daily_energy
    cycle: daily
    tariffs: stnd
  energy_monthly_tvps4:
    source: sensor.digma_100s_tvps4_total_daily_energy
    cycle: monthly
    tariffs: stnd
  energy_yearly_tvps4:
    source: sensor.digma_100s_tvps4_total_daily_energy
    cycle: yearly
    tariffs: stnd

  energy_hourly_pc:
    source: sensor.digma_100s_pc_total_daily_energy
    cycle: hourly
    tariffs: stnd
  energy_daily_pc:
    source: sensor.digma_100s_pc_total_daily_energy
    cycle: daily
    tariffs: stnd
  energy_monthly_pc:
    source: sensor.digma_100s_pc_total_daily_energy
    cycle: monthly
    tariffs: stnd
  energy_yearly_pc:
    source: sensor.digma_100s_pc_total_daily_energy
    cycle: yearly
    tariffs: stnd

  energy_hourly_dishwasher:
    source: sensor.digma_160m_dishwasher_total_daily_energy
    cycle: hourly
    tariffs: stnd
  energy_daily_dishwasher:
    source: sensor.digma_160m_dishwasher_total_daily_energy
    cycle: daily
    tariffs: stnd
  energy_monthly_dishwasher:
    source: sensor.digma_160m_dishwasher_total_daily_energy
    cycle: monthly
    tariffs: stnd
  energy_yearly_dishwasher:
    source: sensor.digma_160m_dishwasher_total_daily_energy
    cycle: yearly
    tariffs: stnd

  energy_hourly_impulse_counter:
    source: sensor.power_meter_indicator
    cycle: hourly
    tariffs: stnd
  energy_daily_impulse_counter:
    source: sensor.power_meter_indicator
    cycle: daily
    tariffs: stnd
  energy_monthly_impulse_counter:
    source: sensor.power_meter_indicator
    cycle: monthly
    tariffs: stnd
  energy_yearly_impulse_counter:
    source: sensor.power_meter_indicator
    cycle: yearly
    tariffs: stnd

sensor:
  - platform: template
    sensors:
      power_meter_translate_value:
        unit_of_measurement: "imp"
        # Если получаем значение от счетчика, учитываем его
        # Если не получаем, оставляем прежнее значение
        value_template: >-
          {% if (states.sensor.power_meter_impulse_counter_total_impulse.state |int > 0) %}
            {{ states.sensor.power_meter_impulse_counter_total_impulse.state }}
          {% else %}
            {{ states.sensor.power_meter_translate_value.state }}
          {% endif %}

  - platform: template
    sensors:
      power_meter_indicator:
        # Полное значение энергии в импульсах приводим к кВтч
        value_template: "{{ states.sensor.power_meter_translate_value.state |float / 3200.0 }}"
        unit_of_measurement: "kWh"

  - platform: template
    sensors:
      power_meter_power:
        # Среднюю мощность в импульсах за предыдущую минуту преобразуем кВт
        value_template: "{{ states.sensor.power_meter_impulse_counter_pulse_counter.state |float * 60.0 / 3200.0 }}"
        unit_of_measurement: "kW"

input_number:
  energy_indicator_value:
    name: Energy Indicator Value
    #initial: "{{ states.sensor.power_meter_indicator.state | float }}"
    min: 0
    max: 999999.9
    step: 0.1
    mode: box

script:
  write_energy_indicator:
    sequence:
      service: python_script.set_state
      data_template:
        entity_id: sensor.power_meter_impulse_counter_total_impulse
        state: "{{ states.input_number.energy_indicator_value.state | float * 3200.0 }}"