- platform: template
  sensors:
    power_meter_translate_value:
      unit_of_measurement: "imp"
      # Если получаем значение от счетчика, учитываем его
      # Если не получаем, оставляем прежнее значение
      value_template: >-
        {% if (states.sensor.power_meter_impulse_counter_total_impulse.state |int > 0) %}
          {{ states.sensor.power_meter_impulse_counter_total_impulse.state }}
        {% else %}
          {{ states.sensor.power_meter_translate_value.state }}
        {% endif %}

- platform: template
  sensors:
    power_meter_indicator:
      # Полное значение энергии в импульсах приводим к кВтч
      value_template: "{{ states.sensor.power_meter_translate_value.state | float / 3200.0 }}"
      unit_of_measurement: "kWh"

- platform: template
  sensors:
    power_meter_power:
      # Среднюю мощность в импульсах за предыдущую минуту преобразуем кВт
      value_template: "{{ states.sensor.power_meter_impulse_counter_pulse_counter.state |float * 60.0 / 3200.0 }}"
      unit_of_measurement: "kW"
