- platform: template
  sensors:
    vacuum_cleaner_status_sensor:
      friendly_name: "Vacuum Cleaner Status Sensor"
      value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"

    vacuum_cleaner_error_sensor:
      friendly_name: "Vacuum Cleaner Error Sensor"
      value_template: >
        {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.error is defined %}
          {{states.vacuum.xiaomi_vacuum_cleaner.attributes.error}}
        {% else %}
          No Error
        {% endif %}

- platform: mqtt
  state_topic: "valetudo/rockrobo/state"
#  json_attributes_topic: "valetudo/rockrobo/map_data_parsed"
  json_attributes_topic: "valetudo/rockrobo/map_data_parsed"
  name: xiaomi_map
  value_template: "OK"
