# BlitzWolf BW-SHP6 10A Power Monitoring Plug
# https://templates.blakadder.com/blitzwolf_SHP6.html
substitutions:
#  plug_name: smart_power_d100
  #plug_name: power_meter_relay_digma100s_balkoon
  plug_name: digma_160m_dishwasher 
  # Higher value gives lower watt readout
  current_res: "0.001254"
  #current_res: "0.003"
  voltage_div: "912"
  
#https://www.ixbt.com/live/comfort/blitzwolf-bw-shp8-wi-fi-rozetka-s-energomonitoringom-obzor-proshivka-esphome-home-assistant.html
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285
#  on_boot:
#    priority: -10
#    then:
    # on affter boot
    #- switch.toggle: relay
#     - switch.turn_on: relay

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
  password: !secret api_passwd
ota:
  password: !secret ota_passwd

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_passwd

time:
  - platform: homeassistant
    id: homeassistant_time
#    timezone: "Asia/Yekaterinburg"

status_led:
  pin: 
    number: GPIO1
    inverted: True

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO3
      inverted: True
    on_press:
      - switch.toggle: relay
    name: "${plug_name}_button"
  - platform: status     
    name: "${plug_name}_Status"
        
switch:
  - platform: gpio
    name: "${plug_name}_Relay"
    id: relay
    pin: GPIO14
    restore_mode: ALWAYS_ON
#    on_turn_on:
#      - switch.turn_on: "${plug_name}_LED_Blue"
    on_turn_off:
#      - switch.turn_off: "${plug_name}_LED_Blue"
      - switch.turn_off: "${plug_name}_LED_Red"
#  - platform: gpio
#    internal: true
#    name: "${plug_name}_LED_Blue"
#    id: "${plug_name}_LED_Blue"
#    pin: GPIO1
#    inverted: True
  - platform: gpio
    name: "${plug_name}_LED_Red"
    internal: true
    id: "${plug_name}_LED_Red"
    pin: GPIO13
    inverted: True
    
  - platform: restart
    name: "${plug_name}_restart"
    
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${plug_name}_Current"
      icon: mdi:current-ac
      unit_of_measurement: 'A'
      accuracy_decimals: 3
    voltage:
      name: "${plug_name}_Voltage"
      icon: mdi:flash-circle
      unit_of_measurement: 'V'
      accuracy_decimals: 0
    power:
      name: "${plug_name}_Power"
      icon: mdi:flash-outline
      unit_of_measurement: 'W'
      accuracy_decimals: 2
      id: "${plug_name}_Power"
      filters:
        - multiply: 0.54
      on_value_range:
        - above: 1.0
          then:
            - switch.turn_on: "${plug_name}_LED_Red"
        - below: 1.0
          then:
            - switch.turn_off: "${plug_name}_LED_Red"
    change_mode_every: 4
    update_interval: 10s

#Потребление за день
  - platform: total_daily_energy
    name: "${plug_name}_Total Daily Energy"
    power_id: "${plug_name}_Power"
    id: "${plug_name}_daily_energy"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "${plug_name}_Uptime"
    unit_of_measurement: days
    update_interval: 600s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: "${plug_name}_WiFi_Signal"
    update_interval: 600s

text_sensor:
  - platform: version
    name: "${plug_name}_firmware_version"