substitutions:
  plug_name: kitchen_ir

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 10 #db

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd
ota:
  password: !secret ota_passwd

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_passwd

binary_sensor:
  - platform: status
    name: "${plug_name}_Status"

remote_transmitter:
  pin:
    number: D2
  carrier_duty_percent: 50%

sensor:
  - platform: uptime
    name: "${plug_name}_Uptime"
    unit_of_measurement: days
    update_interval: 600s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: "${plug_name}_WiFi_Signal"
    update_interval: 600s

switch:
  - platform: template
    name: "${plug_name}_LG TV power on"
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DF10EF
          nbits: 32
          
  - platform: restart
    name: "${plug_name}_restart"
    
text_sensor:
  - platform: version
    name: "${plug_name}_firmware_version"