substitutions:
  plug_name: 'power_meter'

esphome:
  name: ${plug_name}
  platform: ESP32
  board: lolin32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info ###debug ##info

api:
  password: !secret api_passwd

ota:
  password: !secret ota_passwd

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_passwd

time:
  - platform: homeassistant
    id: homeassistant_time

globals:
  - id: '${plug_name}_remember'
    type: uint
    restore_value: yes
    initial_value: '0'
    
  - id: '${plug_name}_blink'
    type: uint
    restore_value: no
    initial_value: '0'

sensor:
  - platform: template
    internal: false
    name: '${plug_name}_remember'
    lambda: |-
      return id(${plug_name}_remember);

  - platform: template
    name: '${plug_name}_pulse_counter'
    id: '${plug_name}_pulse_counter'
    force_update: true                  ### Иначе будет тротлить одинаковые значения
    lambda: |-
        uint result = 0;
        uint blink_1m = id(${plug_name}_blink);
        uint rem = id(${plug_name}_remember);
        id(${plug_name}_blink) = 0;

        if ( id(${plug_name}_Status).state ) {
          result = blink_1m + rem;
          if ( id(${plug_name}_remember) > 0 ) {
            id(${plug_name}_remember) = 0;
          }
        } else  {
          id(${plug_name}_remember) = rem + blink_1m;
        }
        return result;

  - platform: uptime
    name: '${plug_name}_Uptime'
    unit_of_measurement: days
    update_interval: 600s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: '${plug_name}_WiFi_Signal'
    update_interval: 600s

binary_sensor:
  - platform: status
    name: '${plug_name}_Status'
    id: '${plug_name}_Status'

### Ловим импульсы длительностью 150-250мс, они и есть наш полезный сигнал на воне 50Гц шума
  - platform: gpio
    device_class: power
    internal: true
    pin: 
      number: 32
      inverted: true
      mode: INPUT_PULLUP
    name: '${plug_name}_blink'
    on_click:
      - min_length: 80ms
        max_length: 200ms
        then:
          - lambda: id(${plug_name}_blink) += 1;

text_sensor:
  - platform: version
    name: '${plug_name}_firmware_version'

switch:
  - platform: restart
    name: '${plug_name}_restart'
