substitutions:
  plug_name: terrarium_bedroom

esphome:
  name: ${plug_name}
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
  password: !secret api_passwd
ota:
  password: !secret ota_passwd

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_passwd

time:
  - platform: homeassistant
    id: homeassistant_time

dallas:
#  - pin: 12
  - pin: 14

light:
  - platform: binary
    name: "${plug_name}_Pomp"
    output: ${plug_name}_light_1
    restore_mode: ALWAYS_ON
    
  - platform: binary
    name: "${plug_name}_Lamp"
    output: ${plug_name}_light_2

output:
  - platform: gpio
    id: "${plug_name}_light_1"
    inverted: true
    pin: 25

  - platform: gpio
    id: "${plug_name}_light_2"
    inverted: true
    pin: 27

binary_sensor:
  - platform: status
    name: "${plug_name}_Status"

  - platform: gpio
    name: "${plug_name}_WaterLeak1"
    pin:
      number: 18
      inverted: True
      mode: INPUT_PULLUP
    filters:
     - delayed_off: 3h

sensor:
  - platform: dallas
    address: 0x9D019B7307010C28
    name: "${plug_name}_Ambient_Temp"

  - platform: dallas
    address: 0x2F01144B1B39AA28
    name: "${plug_name}_Aqua_Temp"

  - platform: uptime
    name: "${plug_name}_Uptime"
    unit_of_measurement: days
    update_interval: 600s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: "${plug_name}_WiFi_Signal"
    update_interval: 600s

switch:
  - platform: restart
    name: "${plug_name}_restart"

text_sensor:
  - platform: version
    name: "${plug_name}_firmware_version"